- src/main.ts
> feat: use production branch in pipeline

- src/DnsStage.ts
- src/IamStage.ts
- src/PipelineStack.ts
> feat: split iam and dns into two stages

- src/CspZoneIamPolicyStack.ts
> fix: add additional action to delegation policy

- .projen/tasks.json
- .projenrc.js
- src/CspStage.ts
- src/CspZoneIamPolicyStack.ts
- src/CspZoneStack.ts
- src/PipelineStack.ts
- src/Statics.ts
- src/SubzoneStack.ts
> feat: introduce account global parameters for finding csp-nijmegen zone

- src/PipelineStack.ts
> fix: wrong stage order in pipeline

- src/AccountStage.ts
- src/CspNijmegenStack.ts
- src/CspNijmegenStage.ts
- src/DnsStack.ts
- src/PipelineStack.ts
- test/main.test.ts
- Removed secondary accp stack
- Prepare for enabling existing stack to deploy the hostedzone
- Fixed tests
> feat: removed secondary accp stack

- src/DnsSecStack.ts
Cannot enable dnssec before the ksk is created...
> fix: deploy ksk before enabling dnssec

- src/AccountStage.ts
- src/CspNijmegenStack.ts
- src/CspNijmegenStage.ts
- src/DnsSecStack.ts
- src/DnsStack.ts
- src/PipelineStack.ts
- src/Statics.ts
- src/main.ts
- test/main.test.ts
Uitrollen auth-prod hosted zone inclusief DNSSEC en van NS records in csp-nijmegen.nl
> feat: AccountStage for auth-prod

- src/AccountStage.ts
- src/CspNijmegenStage.ts
- src/DnsRootStack.ts
- src/DnsRootStage.ts
- src/DnsSecStack.ts
- src/PipelineStack.ts
- test/main.test.ts
- Verwijderen dnssec-stack met kms key uit CspNijmegenStage
- Opruimen tijdelijke parameter in dnssec-stack
- Voorbereiding op komst DNS account met nieuwe dns-root-stage
> feat: verwijder kms uit CspNijmegenStage

- src/PipelineStack.ts
- src/TempAuthAccpStage.ts
Try to see if we can move the subdomains like this.
Check if subdomain NS records are retained in old csp-nijmegen.nl hosted zone!
> feat: switch sandbox subdomain to new csp-nijmegen.nl hosted zone

- src/PipelineStack.ts
Now we are prety sure acceptance can be moved without problems
> feat: move accp hosted zone to new csp-nijmegen.nl hosted zone

- src/DnsRootStack.ts
- src/PipelineStack.ts
- src/TempAuthProdStage.ts
deploy mijn-nijmegen dns records in csp-nijmegen.nl from here so we can safely switch dns
> feat: deploy mijn-nijmegen dns records in csp-nijmegen.nl

- src/DnsRootStack.ts
Fixes https://github.com/GemeenteNijmegen/webformulieren/issues/424
> feat: update records for mtls certs used by esb

- .projen/deps.json
- .projenrc.js
- package.json
- src/DnsStack.ts
- yarn.lock
> feat: deploy account root zone parameters to us-east-1

- src/PipelineStack.ts
- src/Statics.ts
- yarn.lock
- deploy test-3 subdomain to test-3 account
- deploy test-4 subdomain to test-4 account
> feat: test-3 and test-4 subdomains

- src/DnsConfiguration.ts
> fix: wrong stage names for generiek accounts

- src/DnsRootStack.ts
- yarn.lock
- forward yivi-accp.csp-nijmegen.nl to hosted zone in new lz
> feat: forward for yivi-accp subdomain

- src/DnsRootStack.ts
part of https://github.com/GemeenteNijmegen/tribe-brp-linker/issues/82
> feat: Add NS records for tribe accp new LZ

- src/DnsRootStack.ts
> feat: add yivi-brp-issue subdomain

- src/DnsConfiguration.ts
- src/Statics.ts
> feat: add component library

- src/DnsRootStack.ts
> feat: add NS and DS record for component library dev

- src/DnsRootStack.ts
Add redirect records for gn-yivi-prod account
> feat: add records for gn-yivi-prod account

- src/DnsRootStack.ts
> feat: Add NS records for Tribe Prod in new LZ

- src/DnsRootStack.ts
- Add NS and DS records for mijn-nijmegen accounts (accp and prod)
> feat: setup mijn nijmegen forward records

- src/DnsRootStack.ts
> fix: trying to fix the cloudformation state

- src/DnsRootStack.ts
- yarn.lock
Add forwarding for new accounts: 
- webforms-dev
- webforms-accp
- webforms-prod
- static-websites
> feat: add forwarding for new lz accounts (webforms and static sites)

- src/DnsRootStack.ts
> feat: Add ns records for component library accp

- src/DnsConfiguration.ts
- src/Statics.ts
The accounts test-2/5 and um-demo are closed, this removes them (and hopefully fixes the pipeline).
Fixes #
> feat: remove unused accounts

- src/DnsRootStack.ts
Adds NS records for component library prod
Fixes #
> feat: Add NS records for component library

- src/DnsRootStack.ts
> feat: Add ds record for component library accp

- src/DnsConfiguration.ts
- src/Statics.ts
> chore: Remove unused accounts

- src/DnsRootStack.ts
> fix: NS records for component accp

- src/DnsRootStack.ts
> feat: Add DS record for component library prod

- src/DnsRootStack.ts
Fixes https://github.com/GemeenteNijmegen/devops/issues/409
> chore: update cname records irma issue and tribe brp

- src/DnsRootStack.ts
Fixes https://github.com/GemeenteNijmegen/devops/issues/409
> chore: update cname records irma issue and tribe brp main

- src/DnsRootStack.ts
> feat: add NS record for sandbox-marnix

- src/DnsRootStack.ts
Added CNAME Record for DocPOC Acceptatie Sectigo
> feat: cname record update docpoc acceptatie

- src/DnsConfiguration.ts
- src/Statics.ts
Add sandbox-01 subdomain for old lz
> feat: add sandbox 01 subdomain

- src/DnsRootStack.ts
- added ns record for sandbox 01
> feat: added ns record for sandbox 01

- src/DnsRootStack.ts
> feat: Add NS records for submission storage

- src/DnsConfiguration.ts
- src/Statics.ts
> feat: add gn-yivi-nijmegen accounts

- src/DnsRootStack.ts
> feat: add gn-yivi-nijmegen account forwarding

- src/DnsRootStack.ts
Required for https://github.com/GemeenteNijmegen/webformulieren-submissionstorage/issues/73
> feat: Add NS records for submission storage accp

- src/DnsRootStack.ts
> feat: added forwarding for sociale recherche

- package.json
- src/DnsSecStack.ts
- yarn.lock
> chore: upgrade dnssec-record construct

- package.json
- src/DnsConfiguration.ts
- src/DnsRootStack.ts
- yarn.lock
> chore: allow assumed role to poll for status

- .eslintrc.json
- .github/workflows/release.yml
- .projen/deps.json
- package.json
- src/Configuration.ts
- src/DnsConfiguration.ts
- src/Statics.ts
- tsconfig.json
- yarn.lock
- Add dns to new gn-mijn-nijmegen-dev account
- Remove unused vars in statics file
- Upgrade dependencies
> feat: added mijn-nijmegen dev account

- src/DnsConfiguration.ts
- src/Statics.ts
> feat: add subdomains for mijn-services accounts

- src/DnsConfiguration.ts
- src/Statics.ts
> feat: add haal centraal brp dev

- src/Configuration.ts
> feat: auth acc cname toegevoegd

- src/Configuration.ts
> feat: cname brp haal centraal dev

- src/Configuration.ts
> feat: brp haal centraal prod

- src/DnsConfiguration.ts
- src/Statics.ts
> feat: add open-forms subdomains

- src/Configuration.ts
> feat: Irma validation records

- src/Configuration.ts
> feat: tribe brp generiek acc and prod cname

- src/DnsConfiguration.ts
- src/Statics.ts
https://github.com/GemeenteNijmegen/devops/issues/846
> feat: added vwi domains devops

- src/Configuration.ts
> feat: vwi accp cname

- src/Configuration.ts
> feat: vwi-prod cname

- src/Configuration.ts
Last cname
mijn-nijmegen-accp-haal-centraal.csp-nijmegen.nl
> chore: cname for mijn-nijmegen-accp-haal-centraal.csp-nijmegen

- src/Configuration.ts
> chore: add cnames for new mijn-nijmegen certs

- src/DnsConfiguration.ts
> feat: tribe dnssec accp

- src/DnsConfiguration.ts
> feat: add geodata-accp

- src/DnsConfiguration.ts
Fixes #909
https://github.com/GemeenteNijmegen/devops/issues/909
> feat: add geodata domain

- src/DnsConfiguration.ts
- src/Statics.ts
> feat: Add mijn services dev
